// This whole project is generated by ChatGPT just by uploading the UML diagram which is made by me.
package NotificationSystem;



public class  Main {
    public static void main(String[] args) {
        NotificationObservable observable = new NotificationObservable();

        EmailObserver emailObserver = new EmailObserver("user@example.com", observable);
        SMSObserver smsObserver = new SMSObserver("+911234567890", observable);

        observable.addObserver(emailObserver);
        observable.addObserver(smsObserver);

        Singleton_NotificationService service = Singleton_NotificationService.getInstance();
        service.setObservable(observable);

        Notification normal = new NormalNotification("Server Down!");
        Notification gif = new GIFDecoratorNotification(normal);
        Notification pdf = new PDFDecoratorNotification(gif);

        service.setNotification(pdf);
    }
}
